### ISSUE TITLE
 refresh_required?

### ISSUE THREAD

**Issue by abenzick** [dennisvang/tufup#33]
In the tufup.client.Client API, what does the refresh_required flag do?

I'm to the point where the app opens, downloads the new update and alerts the user and then just closes. Trying to think through the best way to present this scenario to the user. I guess auto opening the app again after update isn't a thing is it?

**Comment by dennisvang** [comment]
>In the tufup.client.Client API, what does the refresh_required flag do?

@abenzick During a "refresh", `tufup` tries to contact your update-server to download any new versions of the TUF metadata files.

If the `refresh_required` flag is `True`, `tufup` will close the application if it fails to refresh its metadata.
This can be used e.g. to prevent your app from starting if your update-server cannot be reached.

By [default][1], `refresh_required` is `False`, meaning that `tufup` simply skips the update process if it fails to refresh, and your application can continue normally.

> I'm to the point where the app opens, downloads the new update and alerts the user and then just closes. Trying to think through the best way to present this scenario to the user. I guess auto opening the app again after update isn't a thing is it?

Not sure I understand completely. Could you explain what is happening in a bit more detail?

In any case, the default install function (for Windows) simply starts a process to copy the update files, then exits the application, as can be seen [here][2]. It does *not* restart the application.

If you would like to restart your application automatically after the update is installed, you would have to write your own `install` function, similar to [install_update()][4], and pass that along to the [Client.download_and_apply_update()][3] method.

Otherwise, you could e.g. warn the user that the app will be closed, before starting the update installation.

[1]: https://github.com/dennisvang/tufup/blob/bb7b42004a6621a254aa5559a6019092839705db/src/tufup/client.py#L37
[2]: https://github.com/dennisvang/tufup/blob/bb7b42004a6621a254aa5559a6019092839705db/src/tufup/utils/platform_specific.py#L127
[3]: https://github.com/dennisvang/tufup/blob/bb7b42004a6621a254aa5559a6019092839705db/src/tufup/client.py#L97
[4]: https://github.com/dennisvang/tufup/blob/bb7b42004a6621a254aa5559a6019092839705db/src/tufup/utils/platform_specific.py#L20

**Comment by abenzick** [comment]
Good stuff. I have things fully functioning now. This is an incredibly clean project! Thank you for it and I hope you are able to keep it going.

**Comment by dennisvang** [comment]
Thanks for the kind words! :)
Closing this issue now.
