### ISSUE TITLE
Large patch sizes

### ISSUE THREAD

**Issue by mchaniotakis** [dennisvang/tufup#69]
**Describe the bug**
I have generated a Version 1 of a python application buddled with pyinstaller. This package contains images, libraries, the .exe and my .py files that have been converted to .pyd (binaries). One of those .pyd files states the version of the file. If only change the version of that .pyd file without running pyinstaller again to generate the second version of the bundle with tufup I get a file difference of 200MB, which is crazy if you take into account that the whole package is 340MB. The last modification date for these files are the same except the .pyd file file that states the version. Using the bsdiff4.file_diff() method between these two version produces the same result. I can provide both of these files If needed.

**To Reproduce**
1. Run cython and pyinstaller with .spec required to make the bundle.
2. Copy all files except 1 folder containing some images
3. Modify version.py file and re-run cython for that file to generate version.pyd and copy over the 1 folder mentioned above from the source (folder has not changed and copied with shutil.cptree() so the modification dates are the same)
4. When I run the  repo.add_bundle(new_bundle_dir=bundle_dir) method I get the filesize mentioned above for the patch

**Expected behavior**
A patch size that is less than 10 MB. On a previous run, I regenerated just the .exe (running pyinstaller and just copying the .exe and deleting everything else while I follow the steps mentioned above.) The .exe filesize is 17mb while the generated patch was 35MB for that run.

**System info (please complete the following information):**
 - OS: [Window 11]
 - Python version 3.9
 - Pyinstaller version 5.9.0
 - Tufup version 0.4.9
 - bsdiff4 version 1.2.3

**Comment by dennisvang** [comment]
@mchaniotakis Thanks for providing such a detailed report.

You are right, these excessively large patches for small changes are not very useful.

Tufup was created as a replacement for PyUpdater (because PyUpdater is no longer maintained). For this reason, the [patch creation in tufup][3] using `bsdiff4` is basically a *naive* copy of PyUpdater's [`make_patch`][1] (see inputs [here][2]).

Although I did add some tests for basic patch functionality, I must admit, I haven't paid very much attention to the resulting file sizes.

The use of bsdiff4, in itself, does not seem to be a problem. Rather, the problem comes from the fact that we use it, naively, to create binary differences of `.tar.gz` archives.

It appears that binary diffs of either uncompressed `.tar` files or non-tar `.gz` files are okay, but binary diffs of `.tar.gz` files are troublesome (the diffs are correct, but very large).

There's probably a good explanation for this, so I'll have a closer look at it as soon as I have some free time.

[1]: https://github.com/Digital-Sapphire/PyUpdater/blob/282760de71ea6501b90d90d85b5fc6ad1d0c2bd8/pyupdater/core/package_handler/patch.py#L43
[2]: https://github.com/Digital-Sapphire/PyUpdater/blob/282760de71ea6501b90d90d85b5fc6ad1d0c2bd8/pyupdater/core/package_handler/__init__.py#L196
[3]: https://github.com/dennisvang/tufup/blob/73d8a240a32e4aa4d420a784deb0862a7581616c/src/tufup/common.py#L128

**Comment by dennisvang** [comment]
As a temporary workaround, patches can be disabled using `--skip-patches`,  see PR #68.

**Comment by dennisvang** [comment]
Another problem (or perhaps the main problem?) may be the fact that pyinstaller builds are not reproducible by default, as [explained in the docs][1]:

>In certain cases it is important that when you build the same application twice, using exactly the same set of dependencies, the two bundles should be exactly, bit-for-bit identical.
>
>That is not the case normally. Python uses a random hash to make dicts and other hashed types, and this affects compiled byte-code as well as PyInstaller internal data structures. As a result, two builds may not produce bit-for-bit identical results even when all the components of the application bundle are the same and the two applications execute in identical ways.
 
but

>You can ensure that a build will produce the same bits by setting the [PYTHONHASHSEED](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHASHSEED) environment variable to a known integer value before running PyInstaller. [...]

[1]: https://pyinstaller.org/en/stable/advanced-topics.html#creating-a-reproducible-build

**Comment by dennisvang** [comment]
more useful information:
- https://try.diffoscope.org
- https://reproducible-builds.org/docs/archives/

**Comment by dennisvang** [comment]
Although we can now work around most of the issues with reproducibility with `gzip`, one risk remains:

The compressed output from gzip depends on the implementation, and there is *no guarantee* that identical input will lead to identical output between different implementations.

We assume that the tufup archives are created on the same OS that they are used on, and that the gzip implementation is sufficiently stable between versions of the same OS to guarantee byte-for-byte equality. 

However, this may lead to trouble in the future. If it turns out that gzip output is unstable between different versions of the *same* OS, the `python-tuf` hash check would fail, preventing updates.

There are a few options to prevent this: 
  
- Implement support for OS versions in the archive filename, so we can add separate targets for different OSes (or OS versions). This is also in line with multi-platform support as in #79. 
- Register the `.tar` archives as targets, instead of `.tar.gz` archives. This would simplify our code, because we would no longer need to worry about gzip reproducibility. To save disk space on the client we could still keep a compressed archive there using the *default* gzip. Note that gzip compression could still be used for file transmission, e.g. using the `Content-Encoding: gzip` HTTP-header, but this would depend on the user's update-server configuration and would therefore be outside the scope of tufup (`python-tuf` automatically handles decompression if that HTTP-header is set).

**Comment by dennisvang** [comment]
After some more thought, here's another option:

We stick with compressed archives (`.tar.gz`) as our tuf repository targets.

This means the download verification process and the server configuration can remain unaltered.

However:

- we take [precautions][1] to ensure that out (uncompressed) `.tar` archives are reproducible
- we create a (monolithic) patch file using `bsdiff4` from the (uncompressed) `.tar` archives
- we include a file hash for the (uncompressed) *destination* `.tar` archive in the target metadata for the *patch* file, using a [CUSTOM object][2] 
- after reconstructing the *destination* archive from the *patch*, on the client side, we verify its integrity using the hash from the custom metadata object, *before* gzipping the archive (just to save storage space)

The only problem remaining now is that our uncompressed `.tar` archives can be two or three times the size of the corresponding `.tar.gz` files. This may cause trouble due to resource limitations, as `bsdiff4` [requires a lot of memory][3] (and time).

In addition, we should implement some kind of failsafe, so that failed patches will be ignored on the next run, in favor of a full installation.

[1]: https://reproducible-builds.org/docs/archives/#full-example
[2]: https://theupdateframework.github.io/specification/latest/#targets-obj-targets
[3]: https://www.daemonology.net/bsdiff/

**Comment by dennisvang** [comment]
> Tufup was created as a replacement for PyUpdater (because PyUpdater is no longer maintained). For this reason, the [patch creation in tufup](https://github.com/dennisvang/tufup/blob/73d8a240a32e4aa4d420a784deb0862a7581616c/src/tufup/common.py#L128) using `bsdiff4` is basically a _naive_ copy of PyUpdater's [`make_patch`](https://github.com/Digital-Sapphire/PyUpdater/blob/282760de71ea6501b90d90d85b5fc6ad1d0c2bd8/pyupdater/core/package_handler/patch.py#L43) (see inputs [here](https://github.com/Digital-Sapphire/PyUpdater/blob/282760de71ea6501b90d90d85b5fc6ad1d0c2bd8/pyupdater/core/package_handler/__init__.py#L196)).
> 
> Although I did add some [tests for basic patch functionality](https://github.com/dennisvang/tufup/blob/73d8a240a32e4aa4d420a784deb0862a7581616c/tests/test_common.py#L125), I must admit, I haven't paid very much attention to the resulting file sizes.

For completeness, it turns out a similar issue also arose with pyupdater using `.tar.gz`, but not using `.zip` (default on windows): https://github.com/Digital-Sapphire/PyUpdater/issues/121
