### ISSUE TITLE
Command Line Interface - Discussion

### ISSUE THREAD

**Issue by JessicaTegner** [dennisvang/tufup#9]
An issue to track discussion regarding the disign and implementation of notsotufs CLI.

**Comment by dennisvang** [comment]
On thing to keep in mind is that `notsotuf` just creates a *standard* [python-tuf ][1] repository.

We only provide some basic convenience methods and shortcuts on top of tuf. We do not touch the metadata nor do we modify the mechanics of the underlying tuf repository.

This implies that the repo tools from `python-tuf`, as well as any CLI tools that are (to be) developed for `python-tuf`, should also work for `notsotuf`.

[1]: https://github.com/theupdateframework/python-tuf

**Comment by NicklasTegner** [comment]
true. But what I saw the cli do would be something like the following

* Generate and store keys
* Sign packages and handling metadata
* moving files into the right places, so you could have something else just go "upload repo to server"

**Comment by dennisvang** [comment]
That's basically what the scripts in [notsotuf-example][1] do:

There's an [init_repo.py][2] and an [add_target_to_repo.py][3], which I intend to be the basis for a CLI. Currently I am still just using them to try out different workflow implementations.

I just made the notsotuf-example repo publicly visible, and it is still very much a work in progress. I still need to adapt it to the latest version of notsotuf. The content is similar to the smaller examples in the `notsotuf/examples` folder.

This project illustrates what an actual application could look like, using both pyinstaller and notsotuf.

This also has to do with issue #8.

[1]: https://github.com/dennisvang/notsotuf-example
[2]: https://github.com/dennisvang/notsotuf-example/blob/master/init_repo.py
[3]: https://github.com/dennisvang/notsotuf-example/blob/master/add_target_to_repo.py

**Comment by NicklasTegner** [comment]
@dennisvang  had a chance to look at dennisvang/notsotuf-example and had the following comments in regards to the cli tool.

* I saw that we had "init_repo.py" and "add_target_to_repo.py", which I think is a perfect example and gives us a good scope for what should be included in the cli


From that, I would say we could have the following commands.

notsotuf of course being the root command.

* init (generate a setting file or something, where you can set paths for where to store stuff. We should have defaults for this)
* key add/remove key pairs (with has like add role keypath encrypted)
* artifact/target (or whatever we call an application tarball) path version (should add the target, create patch)
* sign (don't know if this should be a separate command, might be a good idea, considering multiple workers (Windows and MacOS in a CD environment, writing to the repository to save the new versions in the metadata)

I know you said that uploading to a 3rd party server is out of scope, so haven't included this on purpose.
Looking forward to hearing your thoughts @dennisvang

**Comment by dennisvang** [comment]
See [issue9 branch][1] for an initial attempt.

[1]: https://github.com/dennisvang/notsotuf/tree/issue9

**Comment by NicklasTegner** [comment]
Using __main__.py to call a package is old behaviour.
This can be done through pyproject.toml, so we can name the file and function whatever we like.
See example here <https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html>
I propose we change the name to cli.py so it becomes notsotuf.client:main and then move the cli specific code from __init__.py


I'll comment more, when the pr has been create, so I can comment on specific things.

**Comment by dennisvang** [comment]
@NicklasTegner

> Using main.py to call a package is old behaviour.

As far as I know, __main__.py is still needed in order to support [calling the package][3] directly, as in `python -m notsotuf`. If you  try this call without __main__.py, you'll get `No module named notsotuf.__main__; 'notsotuf' is a package and cannot be directly executed`

*In addition*, an [entry point][1] is already defined in setup.cfg, so pip creates a script allowing us to call `notsotuf ...` directly from the command line.

So, users can call either  `python -m notsotuf ...` or `notsotuf ...` from the command line.

> This can be done through pyproject.toml, so we can name the file and function whatever we like.
See example here https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

As noted in the setup.py file, my plan for the future is to get rid of both setup.cfg and setup.py and only use pyproject.toml.
However, the [project configuration via pyproject.toml][2] is still marked "experimental." As long as that is the case, I wanted to stick to setup.cfg. 

> I propose we change the name to cli.py so it becomes notsotuf.client:main and then move the cli specific code from init.py

As for the name, I'm planning to convert the repo.py module to a package and put a cli.py in there, as the cli is only intended for the repo side.

[1]: https://setuptools.pypa.io/en/latest/userguide/entry_point.html
[2]: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
[3]: https://docs.python.org/3/library/__main__.html#main-py-in-python-packages

**Comment by dennisvang** [comment]
To get on with things, I merged PR #15, so we now have a rudimentary CLI. 

Some features left to do:

- add proper command line feedback
- add documentation
- add command to set thresholds

**Comment by dennisvang** [comment]
... added some command line feedback in pr #19

**Comment by dennisvang** [comment]
@NicklasTegner Added some basic CLI functionality that looks reasonably usable to me.

Perhaps you could give it a try and let me know what you think?

### Examples

Initialize repository by answering some questions on the command line. This creates key pairs and adds them to root:
```bash
notsotuf init
```
Add a new app version from some `my/dist/` folder, sign using keys from some `my/private/keys` folder:

```
notsotuf targets add 1.0.1 my/dist my/private/keys
```

Create a new key pair with encrypted private key, and use this to replace an existing key:
```bash
notsotuf keys name_of_my_new_key -c -e replace name_of_my_old_key my/private/keys
```

Update snapshot expiration date to 2 days from now, and re-sign, show debug information:
```
notsotuf sign -d -e 2 snapshot my/private/keys
```

**Comment by NicklasTegner** [comment]
So I've only test the init command so far and I have the following:

We need sensible defaults. Like most of the places where it says "none" you can't actually answer nothing. And most the questions you don't actually know what mean, unless you know the inner workings of nst or tuf itself.

**Comment by dennisvang** [comment]
@NicklasTegner Thanks for the quick response. Those are some good points. :)

- I'll set some defaults where possible, and provide examples otherwise.
- The cli is still undocumented, but I'm planning to add some explanations regarding the `init` questions.
 
I do think it is imperative to understand the basics of TUF in order to use notsotuf properly.
 
We could add a kind of summary to the documentation, e.g. something along these lines:

- TUF specifies 4 top-level roles: `root`, `targets`, `snapshot`, `timestamp` (see below)
- each role has its own "metadata file" in the repository, e.g. `root.json`
- metadata for each role must be signed after each modification, using one or more private keys, which may be encrypted with password
- metadata for each role has an expiration date, after which it needs to be re-signed
- metadata for each role has a `version` which is incremented after each change (this is done automatically by notsotuf)

Description of top-level roles (see [TUF docs][1] for details and reasoning):

- `root`
    - defines known keys
    - assigns keys to roles (including `root` itself)
    - specifies how many signatures are required for each role  (number of signatures >= `threshold`)
    - modified when keys are added/removed (which should be rare), or upon expiry
- `targets`
    - defines known files, i.e. in our case the archive files and patch files that are available for download
    - modified whenever a new app version is released, or upon expiry
- `snapshot`
    - defines which version of targets metadata is currently valid
    - modified whenever targets role changes, or upon expiry
- `timestamp`
    - defines which version snapshot metadata is currently valid
    - modified whenever snapshot changes, or upon expiry (typically every day)

Although it is *not* recommended, notsotuf allows the use of a single key for multiple roles.

[1]: https://theupdateframework.io/metadata/
